// Generated by https://quicktype.io

export class GetCardFlowAppsByProcessFlowIDDataClass {
    ProcessID:       number;
    Date:            string;
    RoteDateTimeB:   string;
    RoteDateTimeE:   string;
    CardDateTimeB:   string;
    CardDateTimeE:   string;
    DateB:           string;
    DateE:           string;
    DateTimeB:       string;
    DateTimeE:       string;
    EmpID:           string;
    EmpCode:         string;
    EmpNameC:        string;
    TimeB:           string;
    TimeE:           string;
    CauseID1:        string;
    CauseName1:      string;
    CauseID2:        string;
    CauseName2:      string;
    Note:            string;
    Info:            any;
    UploadFile:      UploadFile[];
    MailBody:        any;
    State:           string;
    ExceptionalCode: string;
    ExceptionalName: string;
}

export class UploadFile {
    UploadName:  string;
    ServerName:  string;
    Description: string;
    Blob:        any;
    Type:        string;
    Size:        number;
}
