// Generated by https://quicktype.io

export class DeptSecretaryDataClass {
    DeptSecretaryID: number;
    DeptCode:        string;
    DeptName:        string;
    EmpID:           string;
    EmpName:         string;
    IsValid:         boolean;
    Note:            string;
    UpdateMan:       string;
    UpdateDate:      string;
}
