// Generated by https://quicktype.io

export class GetAllRoleDataClass {
    RoleCode: string;
    RoleName: string;
    isAdmin:  boolean;
    Level:    number;
    uiIsCheck : boolean;
    uiIsDisabled : boolean;
}
