// Generated by https://quicktype.io

export class GetAttendCalendarExceptionalDataClass {
    AttendDate:     string;
    ActualRoteID:   number;
    ActualRoteCode: string;
    ActualRoteName: string;
    OnTime:         string;
    OffTime:        string;
    OnCardTime:     string;
    OffCardTime:    string;
    LateMins:       number;
    EarlyMins:      number;
    IsAbsent:       boolean;
    ForgetCard:     number;
    
    ActualRote_OnTime_calCrossDay: boolean;
    ActualRote_OffTime_calCrossDay: boolean;
    AttendCard_OnTime_calCrossDay: boolean;
    AttendCard_OffTime_calCrossDay: boolean;
}
