// Generated by https://quicktype.io

export interface GetAttendForCardPatchIntegrationData {
    EmpNameC:          any;
    AttendCard:        AttendCard[];
    AttendID:          number;
    EmpID:             string;
    AttendDate:        string;
    RoteID:            number;
    ActualRoteID:      number;
    HolidayRoteID:     number;
    LateMins:          number;
    EarlyMins:         number;
    IsAbsent:          boolean;
    IsAbnormal:        boolean;
    IsFlexibleMinute:  boolean;
    ForgetCard:        number;
    OnBeforeMins:      number;
    OffAfterMins:      number;
    IsBonusLeave:      boolean;
    AttHours:          number;
    Rote:              Rote;
    ActualRote:        Rote;
    HolidayRote:       Rote;
    EliminateLate:     boolean;
    EliminateEarly:    boolean;
    EliminateOnBefore: boolean;
    EliminateOffAfter: boolean;
    EliminateAbsent:   boolean;
    Ride:              boolean;
    Behind:            Behind;
    ArriveTime:        string;
    IsAbs:             boolean;
    IsOt:              boolean;
}

export interface  Behind {
    EmpId: string;
    IsDelay: boolean;
    ArriveTime: string;
    errMsg: any;
    IsTransCar: boolean;
}

export interface Rote {
    RoteID:                number;
    RoteCode:              string;
    RoteNameC:             string;
    DeptCode:              string;
    DeptName:              string;
    OnDateTime:            string;
    OffDateTime:           string;
    OnTime:                string;
    OffTime:               string;
    WorkHours:             number;
    DWorkHours:            number;
    OnTimeEarliest:        number;
    OffTimeLatest:         number;
    OtBeginTime:           any | string;
    YearRestHours:         number;
    LeaveOffTime:          string;
    FlexibleMinute:        number;
    FlexibleMinuteForward: number;
    FlexibleMinuteBehind:  number;
    LateMinute:            number;
    WorkInterval:          number;
    IsCard:                boolean;
    IsShift:               boolean;
    IsDifferShift:         boolean;
    Ride:                  boolean;
    Seq:                   number;
    Holiday:               boolean;
    RoteRest:              any[];
    RoteMapping:           any;
}

export interface AttendCard {
    AttendCardID:  number;
    EmpID:         string;
    CardDate:      string;
    OnTime:        string;
    OnTime48:      any;
    OnDateTime:    string;
    OffTime:       string;
    OffTime48:     any;
    OffDateTime:   string;
    OnTimeForget:  boolean;
    OffTimeForget: boolean;
    NotModify:     boolean;
}
