// Generated by https://quicktype.io

export interface GetAttendCalendarAbsData {
    AttendDate:      string;
    DateTimeB:       string;
    DateTimeE:       string;
    Use:             number;
    HoliDayID:       number;
    HoliDayNameC:    string;
    HoliDayUnit:     string;
    HoliDayUnitName: string;
    SignDateTime:    string;
}
