// Generated by https://quicktype.io

export interface GetCardFlowAppsGetApiDataClass {
    ProcessID:             number;
    Date:                  string;
    RoteDateTimeB:         string;
    RoteDateTimeE:         string;
    CardDateTimeB:         any;
    CardDateTimeE:         any;
    DateB:                 string;
    DateE:                 any;
    DateTimeB:             string;
    DateTimeE:             any;
    EmpID:                 string;
    EmpCode:               string;
    EmpNameC:              string;
    TimeB:                 string;
    TimeE:                 string;
    CauseID1:              string;
    CauseName1:            string;
    CauseID2:              string;
    CauseName2:            string;
    Note:                  string;
    Info:                  any;
    UploadFile:            any[];
    MailBody:              any;
    State:                 string;
    ExceptionalCode:       string;
    ExceptionalName:       string;
    ExceptionalCancelCode: any;
    ExceptionalCancelName: any;
    DeptName:              string;
    JobName:               string;
    ApproveDate:           string;
    ErrorStateCode:          string;
    ErrorStateName:          string;
    uiIsLateMins:            boolean;
    uiIsEarlyMins:           boolean;
    uiIsForgetCard:          boolean;
    uiIsNormal:              boolean;
    uiIsOffAfterMins:        boolean;
    uiIsOnBeforeMins:        boolean;
}
