// Generated by https://quicktype.io

export interface GetEventDateDataClass {
    EventDate:            string;
    BalanceDayHourMinute: BalanceDayHourMinute;
}

export interface BalanceDayHourMinute {
    Day:    number;
    Hour:   number;
    Minute: number;
}
