// Generated by https://quicktype.io

export interface GetEmpInfoDataClass {
    Base:      Base;
    DeptView:  DeptView;
    SchlView:  SchlView[];
    Ttscode:   string;
    WorkState: string;
}

export interface Base {
    Nobr:                string;
    NameC:               string;
    NameE:               string;
    NameP:               string;
    Sex:                 string;
    Birdt:               string;
    Addr1:               string;
    Addr2:               string;
    Tel1:                string;
    Tel2:                string;
    Bbcall:              string;
    Email:               string;
    Gsm:                 string;
    Idno:                string;
    ContMan:             string;
    ContTel:             string;
    ContGsm:             string;
    ContMan2:            string;
    ContTel2:            string;
    ContGsm2:            string;
    Blood:               string;
    Password:            string;
    Postcode1:           string;
    Postcode2:           string;
    BankCode:            string;
    Bankno:              string;
    AccountNo:           string;
    AccountNa:           string;
    Marry:               string;
    Country:             string;
    CountMa:             boolean;
    Army:                string;
    ProMan1:             string;
    ProAddr1:            string;
    ProId1:              string;
    ProTel1:             string;
    ProMan2:             string;
    ProAddr2:            string;
    ProId2:              string;
    ProTel2:             string;
    ArmyType:            string;
    NNobr:               string;
    NobrB:               string;
    Province:            string;
    BornAddr:            string;
    Taxcnt:              number;
    KeyMan:              string;
    KeyDate:             string;
    IdType:              string;
    Taxno:               string;
    Pretax:              number;
    ContRel1:            string;
    ContRel2:            string;
    AccountMa:           string;
    Matno:               string;
    Subtel:              string;
    Photo:               any;
    Up1Name:             string;
    Up1File:             any;
    Up2Name:             string;
    Up2File:             any;
    Up3Name:             string;
    Up3File:             any;
    Up4Name:             string;
    Up4File:             any;
    Up5Name:             string;
    Up5File:             any;
    Basecd:              string;
    NameAd:              string;
    AccountUs:           string;
    AccountCn:           string;
    Nation:              string;
    NhiId:               string;
    AgentNobr1:          any;
    AgentNobr2:          any;
    CandidatesWays:      string;
    YearDate:            string;
    Attend:              any[];
    Award:               any[];
    Cardapp:             any[];
    Contract:            any[];
    Cost:                any[];
    DormitoryManagement: any[];
    InslabCn:            any[];
    Lican:               any[];
    Master:              any[];
    Schl:                any[];
    Tmtable:             any[];
    Works:               any[];
}

export interface DeptView {
    Dept:      string;
    Depta:     string;
    Depts:     string;
    DeptName:  string;
    DeptaName: string;
    DeptsName: string;
    JobName:   string;
}

export interface SchlView {
    Nobr:     string;
    Educcode: string;
    Name:     string;
    Adate:    string;
    Schl1:    string;
    Subj:     string;
    DateB:    string;
    DateE:    string;
    Ok:       boolean;
}
