// Generated by https://quicktype.io

export interface GetEmpAgentDateClass {
    AutoKey: number;
    EmpID:   string;
    DateB:   string;
    DateE:   string;
    KeyMan:  string;
    KeyDate: string;
    IsValid: boolean;
}
