import { DayHourMinuteClass } from "./DayHourMinuteClass";

// Generated by https://quicktype.io

export interface GetFlowViewAbsGetApiDataClass {
    EmpID:             string;
    EmpName:           string;
    DeptName:          string;
    DateTimeB:         string;
    DateTimeE:         string;
    Use:               number;
    UseDayHourMinute:  DayHourMinuteClass;
    BaseHour:          number;
    Today:             boolean;
    AbsCount:          number;
    Appointment:       boolean;
    Key:               string;
    OldKey:            string;
    ProcessFlowID:     number;
    FormName:          string;
    AppEmpID:          string;
    AppEmpName:        string;
    AppDeptName:       string;
    ManageEmpName:     string;
    RealManageEmpName: string;
    State:             string;
    Take:              boolean;
    AbsFlowApps:       any;
    AbscFlowApps:      any;
    CardFlowApps:      any;
    ShiftRoteFlowApps: any;
    Handle:            boolean;
    TransSign:         boolean;
    ListHoliDayNameC:  Array<string>;
}

