// Generated by https://quicktype.io

export interface GetFlowSignCardApiDataClass {
    ProcessFlowID:     number;
    FlowTreeID:        string;
    FlowNodeID:        string;
    ProcessApParmAuto: number;
    EmpCode:           string;
    EmpNameC:          string;
    EmpNameE:          string;
    isApproved:        boolean;
    isSendback:        boolean;
    isPutForward:      boolean;
    WriteEmpCode:      string;
    WriteEmpNameC:     string;
    checkProxy:        boolean;
    ExceptionalName:   string;
    Date:              string;
    RoteCode:          string;
    ErrorStateCode:    string;
    ErrorStateName:    string;
    DateB:             string;
    TimeB:             string;
    DateTimeB:         string;
    DateE:             string;
    TimeE:             string;
    DateTimeE:         string;
}

