// Generated by https://quicktype.io

export interface GetFlowViewCardGetApiDataClass {
    EmpID:             string;
    EmpName:           string;
    DeptName:          string;
    Date:              string;
    DateB:             string;
    TimeB:             string;
    DateTimeB:         string;
    DateE:             string;
    TimeE:             string;
    DateTimeE:         string;
    RoteNameC:         string;
    ErrorState:        string;
    Key:               string;
    ProcessFlowID:     number;
    FormName:          string;
    AppEmpID:          string;
    AppEmpName:        string;
    AppDeptName:       string;
    ManageEmpName:     string;
    RealManageEmpName: string;
    State:             string;
    Take:              boolean;
    TransSign:         boolean;
    AbsFlowApps:       any;
    AbscFlowApps:      any;
    CardFlowApps:      any;
    ShiftRoteFlowApps: any;
    Handle:            boolean;
}

