// Generated by https://quicktype.io

export class GetFormMailDataClass {
    AutoKey: number;
    FormCode: string;
    FormName: string;
    Code: string;
    Name: string;
    Subject: string;
    Body: string;
    Note: string;
    KeyMan: string;
    KeyDate: string;
}
