// Generated by https://quicktype.io

export interface GetFlowSignAbsApiDataClass {
    HolidayName:       string[];
    ProcessFlowID:     number;
    FlowTreeID:        string;
    FlowNodeID:        string;
    ProcessApParmAuto: number;
    EmpCode:           string;
    EmpNameC:          string;
    EmpNameE:          string;
    isApproved:        boolean;
    isSendback:        boolean;
    isPutForward:      boolean;
    WriteEmpCode:      string;
    WriteEmpNameC:     string;
    DateB:             string;
    DateE:             string;
    TimeB:             string;
    TimeE:             string;
    day:               number;
    hour:              number;
    minute:            number;
    numberOfVaData:    number;
    checkProxy:        boolean;
    Appointment:       boolean;
}
