// Generated by https://quicktype.io

export interface GetFlowSignShiftRoteApiDataClass {
    ProcessFlowID:     number;
    FlowTreeID:        string;
    FlowNodeID:        string;
    ProcessApParmAuto: number;
    EmpID1:            string;
    EmpCode1:          string;
    EmpNameC1:         string;
    EmpID2:            string;
    EmpCode2:          string;
    EmpNameC2:         string;
    isApproved:        boolean;
    isSendback:        boolean;
    isPutForward:      boolean;
    WriteEmpCode:      string;
    WriteEmpNameC:     string;
    isDR:              boolean;
    isRR:              boolean;
    isRZ:              boolean;
    dateArray:         string[];
    numberOfVaData:    number;
    checkProxy:        boolean;
}

