// Generated by https://quicktype.io

export interface GetFlowSignAbscApiDataClass {
    ProcessFlowID:     number;
    FlowTreeID:        string;
    FlowNodeID:        string;
    ProcessApParmAuto: number;
    EmpCode:           string;
    EmpNameC:          string;
    EmpNameE:          string;
    HolidayName:       string[];
    Note:              string;
    isApproved:        boolean;
    isSendback:        boolean;
    isPutForward:      boolean;
    WriteEmpCode:      string;
    WriteEmpNameC:     string;
    dateArray:         string[];
    day:               number;
    hour:              number;
    minute:            number;
    numberOfVaData:    number;
    checkProxy:        boolean;
}
