// Generated by https://quicktype.io
export class GetHoliDayByFormData {
    HoliDayID:        number;
    HoliDayCode:      string;
    HoliDayNameC:     string;
    HoliDayUnit:      string;
    HoliDayUnitName:  string;
    MinNum:           number;
    IncludeHoliDay:   boolean;
    MaxNum:           number;
    CheckRestHour:    boolean;
    Sex:              string;
    IsDisplay:        boolean;
    AbsentUnit:       number;
    HoliDayKindID:    number;
    HoliDayFlag:      string;
    Seq:              number;
    AutoCreate:       boolean;
    AutoFlowStart:    boolean;
    AbsentLeave:      boolean;
    Memo:             string;
    IsNotRefRote:     boolean;
    IsDisMinus:       boolean;
    IsDisBalance:     boolean;
    IsDisWithHolding: boolean;
    IsThisYear:       boolean;
    IsCycle:          boolean;
    IsEventDate:      boolean;
    IsKeyName:        boolean;
    AtLeastSum:       number;
}
