// Generated by https://quicktype.io

export interface GetIdentityByEmpIDDataClass {
    IdentityID: number;
    Code:       string;
    NameC:      string;
    NameE:      string;
    Sort:       number;
    BaseHour:   number;
}
