// Generated by https://quicktype.io

export interface GetOtViewGetApiData {
    ApproveDate: string;
    State:       string;
    OtID:        number;
    EmpID:       string;
    DateB:       string;
    TimeB:       string;
    TimeE:       string;
    DateTimeB:   string;
    DateTimeE:   string;
    Hour:        number;
    OtHour:      number;
    RestHour:    number;
    CauseID:     number;
    Memo:        any;
    SalaryYYMM:  any;
    Serno:       any;
    Cause:       any;
}
