// Generated by https://quicktype.io

export interface GetRoteByShiftDataClass {
    RoteID:         number;
    RoteCode:       string;
    RoteNameC:      string;
    OnTime:         string;
    OffTime:        string;
    WorkHours:      number;
    DWorkHours:     number;
    OnTimeEarliest: number;
    OffTimeLatest:  number;
    OtBeginTime:    any;
    YearRestHours:  number;
    LeaveOffTime:   string;
    FlexibleMinute: number;
    LateMinute:     number;
    WorkInterval:   number;
    IsCard:         boolean;
    IsShift:        boolean;
    Ride:           boolean;
    Seq:            number;
    Holiday:        boolean;
    RoteRest:       any[];
    RoteMapping:    any;
}
