// Generated by https://quicktype.io

export interface GetSendMailLogDataClass {
    AutoKey:       number;
    ProcessFlowID: number;
    Key:           string;
    Key1:          string;
    Key2:          string;
    ToAddress:     string;
    Subject:       string;
    Body:          string;
    Success:       boolean;
    KeyMan:        string;
    KeyDate:       string;
}
