// Generated by https://quicktype.io

export interface SettingClass {
    loadbalance:                string;
    OAuthPath:                  string;
    _client_id:                 string;
    _redirect_uri_LinkOuthpage: string;
    apiPostURL:                 string;
    FileUploadType:             string[];
}
