// Generated by https://quicktype.io

export interface ShiftRoteFlowAppsDetailClass {
    ShiftRoteDate: string;
    RoteID1:       number;
    RoteCode1:     string;
    RoteName1:     string;
    RoteID2:       number;
    RoteCode2:     string;
    RoteName2:     string;
}
