// Generated by https://quicktype.io

export class AttendUnusualSaveAndFlowStartClass {
    FlowApp:     AFlowApp;
    FlowDynamic: FlowDynamic;
}

export class AFlowApp {
    FlowApps: FlowAppElement[];
    EmpID:    string;
    EmpCode:  string;
    EmpNameC: string;
    State:    string;
}

export class FlowAppElement {
    EmpID:             string;
    EmpCode:           string;
    EmpNameC:          string;
    Date:              string;
    RoteDateTimeB:     string;
    RoteDateTimeE:     string;
    CardDateTimeB:     string;
    CardDateTimeE:     string;
    EliminateLate:     boolean;
    EliminateEarly:    boolean;
    EliminateAbsent:   boolean;
    EliminateOnBefore: boolean;
    EliminateOffAfter: boolean;
    CauseID:           number;
    CauseName:         string;
    Note:              string;
    Info:              string;
    MailBody:          string;
    State:             string;
    UploadFile:        any[];
    ExceptionalCode:   string;
    ExceptionalName:   string;
    ExceptionalCodeCancel:   string;
    ExceptionalNameCancel:   string;
    RoteID:            number;
    RoteNameC:         string;
}

export class FlowDynamic {
    FlowNode: string;
    RoleID:   string;
    EmpID:    string;
    DeptID:   string;
    PosID:    string;
}
