// Generated by https://quicktype.io

export class CreateRoleGetApiClass {
    RoleCode: string;
    RoleName: string;
    Level:    number;
    SetMan:   string;
	IsAssistant: boolean
	IsIncludeChild:boolean
}
