// Generated by https://quicktype.io

export interface GetAttendInfoByDeptGetApiClass {
    DateB:       string;
    DateE:       string;
    DeptaID:     number;
    ChildDept:   boolean;
    PageCurrent: number;
    PageRows:    number;
    EffectDate:  string;
    Display:     string;
    ListState:   string[];
}
