// Generated by https://quicktype.io

export interface GetAttendSumRoteGetApiClass {
    DateB:      string;
    DateE:      string;
    ListDeptID: any[];
    ListEmpID:  any[];
    ListRoteID: any[];
}
