// Generated by https://quicktype.io

export interface GetAttendWishByDeptaGetApiClass {
    DateB:       string;
    DateE:       string;
    WishTypeID:  string;
    ListState:   string[];
    ListDeptaID: string[];
}
