// Generated by https://quicktype.io

export interface GetFlowSignAbsGetApiClass {
    SignEmpID:      string;
    SignRoleID:     string;
    RealSignEmpID:  string;
    RealSignRoleID: string;
    SignDate:       string;
}