// Generated by https://quicktype.io

export interface GetFlowSignAbsGetApiClass {
    SignEmpID:      string;
    SignRoleID:     string;
    RealSignEmpID:  string;
    RealSignRoleID: string;
    SignDate:       string;
}
// Generated by https://quicktype.io

export interface GetFlowSignAbsDataGetApiClass {
    SignEmpID:      string;
    SignRoleID:     string;
	PageCurrent:    string;
	PageRows:       string;
    RealSignEmpID:  string;
    RealSignRoleID: string;
    SignDate:       string;
}