// Generated by https://quicktype.io

export interface GetHoliDayBalanceFlow {
    EmpID:       string;
    DateB:       string;
    DateE:       string;
    HoliDayID:   any;
    KeyName:     string;
    EventDate:   string;
    ListAbsFlow: null;
}
