// Generated by https://quicktype.io

export interface GetOtCalculateGetApiClass {
    EmpID:        string;
    OtCat:        string;
    DateB:        string;
    DateE:        string;
    TimeB:        string;
    TimeE:        string;
    CauseID:      string;
    RoteID:       string;
    CalculateRes: boolean;
    CalculateAtt: boolean;
    Time24:       boolean;
}
