// Generated by https://quicktype.io

export interface InsertCheckAgentClass {
    RoleIdSource: string;
    EmpIdSource:  string;
    EmpIdTarget:  string;
    DateB:        string;
    DateE:        string;
    KeyMan:       string;
}

