// Generated by https://quicktype.io

export class InsertBaseSpecialFlowGetApiClass {
    SourceEmpID: string;
    TargetEmpID: string;
    Sort:        number;
    Note:        string;
    GroupName:   string;
    KeyMan:      string;
}
