// Generated by https://quicktype.io

export interface OTCheckListGetApiClass {
    RowID:        number;
    EmpID:        string;
    OtCat:        string;
    DateB:        string;
    DateE:        string;
    TimeB:        string;
    TimeE:        string;
    CauseID:      string;
    RoteID:       string;
    Card:         boolean;
    CalculateRes: boolean;
    CalculateAtt: boolean;
    Time24:       boolean;
}
