// Generated by https://quicktype.io

export interface OtSaveGetApiClass {
    EmpID:   string;
    OtCat:   string;
    DateB:   string;
    DateE:   string;
    DateA:   string;
    DateD:   string;
    TimeB:   string;
    TimeE:   string;
    Amount:  number;
    CauseID: string;
    RoteID:  string;
    DeptcID: string;
    Note:    string;
    KeyMan:  string;
    Serno:   string;
    Time24:  boolean;
}
