// Generated by https://quicktype.io

export interface SaveFormMailClass {
    FormCode: string;
    Code:     string;
    Name:     string;
    Subject:  string;
    Body:     string;
    Note:     string;
    KeyMan:   string;
}
