// Generated by https://quicktype.io

export interface ShiftRoteCheckByWeekTypeGetApiClass {
    ShiftRoteBySave: ShiftRoteBySave;
    weekType:        number;
}

export interface ShiftRoteBySave {
    EmpID1:        string;
    EmpID2:        string;
    ShiftRoteDate: ShiftRoteDate[];
}

export interface ShiftRoteDate {
    ShiftDate: string;
    RoteID1:   number;
    RoteID2:   number;
}
