// Generated by https://quicktype.io

export interface TransSignStateGetApiClass {
    ListProcessFlowID: number[];
    enumState:         string;
    EmpID:             string;
    SignEmpID:         string;
}
