// Generated by https://quicktype.io

export class UpdateDeptSecretaryGetApiClass {
    DeptSecretaryID: number;
    DeptCode:        string;
    EmpID:           string;
    IsValid:         boolean;
    Note:            string;
    UpdateMan:       string;
}
