// Generated by https://quicktype.io

export interface UpdateFormInfoGetApiClass {
    FormInfo: FormInfo;
    KeyMan:   string;
}

export interface FormInfo {
    AutoKey:     number;
    FormCode:    string;
    FormName:    string;
    FlowTreeID:  string;
    StdNote:     string;
    CheckNote:   string;
    ViewNote:    string;
    EtcNote:     string;
    DynamicNode: string;
    CustomNode:  string;
    TableName:   string;
}
