// Generated by https://quicktype.io

export interface UpdateDeptHumanGetApiClass {
    DeptHumanID: number;
    DeptCode:    string;
    EmpID:       string;
    IsValid:     boolean;
    Note:        string;
    UpdateMan:   string;
}
