// Generated by https://quicktype.io

export interface GetAbsFlowView {
    ProcessFlowID:     number;
    FormName:          string;
    AppEmpID:          string;
    AppEmpName:        string;
    AppDeptName:       string;
    ManageEmpName:     string;
    RealManageEmpName: any;
    SignDate:          string;
    PendingDay:        number;
    Info:              string;
    State:             string;
    Take:              boolean;
    AbsFlowApps:       AbsFlowApp[];
    AbscFlowApps:      any[];
    CardFlowApps:      any[];
    ShiftRoteFlowApps: any[];
}

export interface AbsFlowApp {
    AutoKey:           number;
    Key:               string;
    DateB:             string;
    DateE:             string;
    DateTimeB:         string;
    DateTimeE:         string;
    EventDate:         any;
    AbsFlowAppsDetail: AbsFlowAppsDetail[];
    EmpID:             string;
    EmpCode:           string;
    EmpNameC:          string;
    RoteID:            number;
    TimeB:             string;
    TimeE:             string;
    HoliDayID:         number;
    HoliDayNameC:      string;
    Use:               number;
    Day:               number;
    Balance:           number;
    HoliDayUnitName:   null;
    AgentNobr1:        null | string;
    AgentName1:        string;
    AgentNote:         string;
    Note:              string;
    Info:              null;
    KeyName:           string;
    UploadFile:        any[];
    MailBody:          null;
    State:             string;
    Today:             boolean;
    Circulate:         boolean;
    Appointment:       boolean;
    ProcessID:         number;
    Serno:             string;
    HoliDayName:       string;
}

export interface AbsFlowAppsDetail {
    DateB:            string;
    DateTimeB:        string;
    DateTimeE:        string;
    AbsFlowAppsTrans: any[];
    State:            null;
    EmpID:            null;
    TimeB:            string;
    TimeE:            string;
    HoliDayID:        number;
    Use:              number;
    RoteRestList:     null;
}
